import csv

class ResonanceController:
    def __init__(self, csv_path):
        self.csv_path = csv_path
        self.performance_map = []
        self.load_map()

    def load_map(self):
        """Reads the CSV generated by the frequency sweep."""
        try:
            with open(self.csv_path, 'r') as file:
                reader = csv.DictReader(file)
                for row in reader:
                    self.performance_map.append({
                        'freq': float(row['Frequency_Hz']),
                        'energy': float(row['Energy_Output'])
                    })
        except FileNotFoundError:
            print(f"Error: {self.csv_path} not found. Run the sweep first!")

    def get_optimal_frequency(self):
        """Finds the frequency with the highest energy output."""
        if not self.performance_map:
            return None
        
        # This is the argmax operation in Python
        optimal = max(self.performance_map, key=lambda x: x['energy'])
        return optimal['freq'], optimal['energy']
      
    def tune_to_demand(self, demand):
        """Finds the frequency required to meet a specific energy demand."""
        # Filter for all frequencies that meet or exceed the demand
        viable_options = [item for item in self.performance_map if item['energy'] >= demand]
        
        if not viable_options:
            return None, "Demand exceeds maximum capacity."
        
        # Return the most efficient (closest) match
        return min(viable_options, key=lambda x: x['energy']), "Tuning successful."
      
